server:
  port: 8080
  servlet:
    context-path: /product
 
# View Resolver setting
spring:
  h2:
    console:
      enabled: true
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    url: jdbc:mysql://localhost:3306/spring-test?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: jpa-test-hikari-pool
      jdbc-url: ${spring.datasource.url}
      username: ${spring.datasource.username}
      password: ${spring.datasource.password}
      maximum-pool-size: 20
      connection-test-query: SELECT 1
      driver-class-name: ${spring.datasource.driver-class-name}
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        generate_statistics: true
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 200
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
